name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install RadGraph
      run: |
        pip install .
    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: pytest_report.xml